### ISSUE TITLE
Use ruby from non standard location

### ISSUE THREAD

**Issue by meireles** [willpearse/phyloGenerator2#15]
Will -- Is is possible to  update the shebang in pG_2.rb to `#!/usr/bin/env ruby`? May work better for people like me that have the handicapped ruby shipped with the OS in `/usr/bin` and a more current version somewhere else. Thx for a great program btw!

**Comment by willpearse** [comment]
No worries! I've made the change - sorry for the delay, but I was getting married (...) so I'm quite pleased to say that shebangs weren't really at the top of my mind :D

I hope all's good with you Dudu - are you coming to ESA? If so, it would be great to see you!
