### ISSUE TITLE
phy_params is not implemented?

### ISSUE THREAD

**Issue by josephwb** [willpearse/phyloGenerator2#16]
I tried the `simple_plants` demo, and when i turn on `phy_params` (specifically, bootstrapping) nothing different happens: it just performs a simple ML search.
Searching through the repo, I see no other mention of `phy_params` other than the [demo yaml file](https://github.com/willpearse/phyloGenerator2/blob/b8d1811183d6a442228f8e01d5eca3b84a6404fc/demo/simple_plants/params.yml), so maybe this is just not yet implemented? I'd diagnose further, but unfortunately have no ruby experience :(

**Comment by josephwb** [comment]
I eked my way through the code to figure out that the correct parameter name should be `phylo_args`. I created a [PR to fix this](https://github.com/willpearse/phyloGenerator2/pull/17).

**Comment by willpearse** [comment]
I'm sorry about this, because this must have been frustrating. I am also incredibly grateful that you both found this bug and then fixed it for me! Thank you!

Please let me know if there's anything I can do to help with whatever you're doing. I most definitely owe you a beer/coffee!

**Comment by josephwb** [comment]
No worries (and it wasn't all that bad); it forced me to try to understand ruby ;)

**Comment by willpearse** [comment]
Hey, Ruby's great! :p

(And I still owe you one!)
